version: '3'
services:
  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "6666:3000"

  prom:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes: 
      - ./config:/config
    command:
      - '-config.file=/config/prometheus.yml'
    